### ISSUE TITLE
API limit reach - inin-ratelimit-reset

### ISSUE THREAD

**Issue by sampolgar** [rjsmith64/py-purecloud-participant-data#1]
It seems the Genesys Cloud Platform reaches an API limit at around 180 conversations displaying error inin-ratelimit-reset. Would it be possible to handle these errors?

**Comment by rjsmith64** [comment]
Hi Samuel, you could do so by adjusting the sleep value from time.sleep(0.2) to time.sleep(0.4). There are more robust ways to handle this since the rate limit can be less than 180 at times.

This project is largely obsolete now. The Analytics jobs API lets you export this data much more efficiently now. It also includes participant data / attributes:

https://developer.mypurecloud.com/api/rest/v2/analytics/conversation_details_job.html

**Comment by sampolgar** [comment]
Dear rjsmith

Thank you very much for your response and thank you for the recommendation for the Analytics Jobs API. I will have a look into it further.

Thank you once again, I sincerely appreciate your help.
